# Generated by Django 2.2.5 on 2021-01-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planirovka', '0002_auto_20210102_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='number_of_floors',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
    ]
