# Generated by Django 2.2.5 on 2021-01-03 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planirovka', '0003_building_number_of_floors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='image',
            new_name='template',
        ),
        migrations.RenameField(
            model_name='floor',
            old_name='image',
            new_name='template',
        ),
    ]
